---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoweb
  namespace: demo
  labels:
    app: demoweb
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.demowebcontainer: glob:0.*
spec:
  selector:
    matchLabels:
      app: demoweb
  template:
    metadata:
      labels:
        app: demoweb
    spec:
      containers:
      - name: demowebcontainer
        image: tscaqtestacreuw.azurecr.io/demo-web:0.3
        ports:
        - containerPort: 80
          name: http
